#!/bin/sh
exec tail -n +3 $0

# set -e
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

HELLO_FILE='/boot/grub/hello.world'

menuentry "Hello, World" {
    echo "Output from file"
    echo $HELLO_FILE
    cat (hd0,1)$HELLO_FILE
    sleep -v -i 10
    echo  'Loading Linux 3.16.0-4-amd64 ...'
    linux /boot/vmlinuz-3.16.0-4-amd64 root=UUID=8a91d6c8-a751-4183-8009-e78452e9b058 ro
    echo  'Loading initial ramdisk ...'
    initrd  /boot/initrd.img-3.16.0-4-amd64
}
